name: Deploy to Digital Ocean Kubernetes Cluster

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set up kubectl
        run: doctl kubernetes cluster kubeconfig save 0ab5b7be-1fd8-44fc-83ca-2e241d0ff318

      - name: Verify cluster connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Add RBAC permissions
        run: make add-rbac

      - name: Upgrade prefect server and worker
        env:
          OAUTH2_CLIENT_ID: ${{ secrets.PREFECT_SERVER_GITHUB_CLIENT_ID }}
          OAUTH2_CLIENT_SECRET: ${{ secrets.PREFECT_SERVER_GITHUB_OAUTH_APP_SECRET }}
          OAUTH2_COOKIE_SECRET: ${{ secrets.PREFECT_SERVER_GITHUB_COOKIE_SECRET }}
        run: make upgrade

      - name: Verify deployment
        run: |
          echo "Waiting for all pods backing services to be ready..."
          
          # Wait for all Prefect server pods to be ready
          echo "Waiting for Prefect server pods..."
          kubectl wait --for=condition=ready pod --selector=app.kubernetes.io/instance=prefect-server -n prefect --timeout=300s
          
          # Wait for all Prefect worker pods to be ready
          echo "Waiting for Prefect worker pods..."
          kubectl wait --for=condition=ready pod --selector=app.kubernetes.io/instance=prefect-worker -n prefect --timeout=300s
          
          # Wait for all OAuth2 proxy pods to be ready
          echo "Waiting for OAuth2 proxy pods..."
          kubectl wait --for=condition=ready pod --selector=app.kubernetes.io/instance=prefect-oauth2-proxy -n prefect --timeout=300s
          
          echo "Deployment status:"
          make status
